[EXP_SETTING]
IQA_MODEL_PATH = './IQA/models/nr_tid_weighted.model'
vis_ir = './datasets/vis_ir_dataset64.h5' #data1_path
oe_ue = './datasets/oe_ue_Y_dataset64.h5' #data2_path
far_near = './datasets/far_near_Y_dataset64.h5' #data3_path
save_path = './models/'
log_path = './logs/'
device = 'cuda:0'
seed = 0

[MODEL]
LAM = 80000 # 400
NUM = 40
EPOCHES = [3, 2, 4]
BATCH_SIZE = 16
PATCH_SIZE = 64
INPUT_SIZE = 224
W_EN = [12, 16, 11]
C = [13, 7, 1]
EPSILON = 1e-5
eps = 1e-8
logging_period = 50
LEARNING_RATE = 0.0001

[MODEL.vis_ir]
W_EN=12
C=13
[MODEL.oe_ue]
W_EN=16
C=7
[MODEL.far_near]
W_EN=11
C=1

